########################################################################################
#   PROJECT DIRECTORIES
########################################################################################
SRCD = src
INCLUDED = include
EXAMPLED = examples
SHADERD = ${SRCD}/shaders
BUILD = build
OBJD = build
EXAMPLEOBJD = ${EXAMPLED}/build
LIBD = lib

########################################################################################
#   COMPILER
########################################################################################
ifdef dev
	CC = python ~/.vim/bin/cc_args.py g++
else
	CC = g++
endif

CFLAGS = -Wall -g -std=c++17 -I ${INCLUDED}
BASIC_LIBS = -lglfw3 -lGL -lX11 -lpthread -lX11 -ldl -lGLEW 
IMAGE_LIBS = -lSOIL
MODEL_LIBS = -lassimp

# OTHER LIBS
#LIBS  = -lglfw3
#LIBS +=	-lGL
#LIBS += -lX11
#LIBS += -lpthread
#LIBS += -ldl
#LIBS += -lGLEW
#LIBS += -lSOIL
#LIBS += -lXi
#LIBS += -lassimp
#LIBS += -lGLU
#LIBS += -lrt
#LIBS += -lXxf86vm
#LIBS += -lXinerama

########################################################################################
#   CLASSES
########################################################################################
_DEBUG_OBJ = DebugTools.o
_SHADERS_OBJ = ${_DEBUG_OBJ} TemplateShader.o Shader.o VertexShader.o FragmentShader.o ShaderProgram.o Texture.o Image.o TextureSampler.o CubeMap.o
_ASSIMP_OBJ = Mesh.o Model.o
_GAMEOBJECTS_OBJ = Camera.o

########################################################################################
#   SHADERS EN OPENGL
########################################################################################
_SHADER_CODE  = MyShader.vert MyShader.frag UniformExercise.frag InterpolationExercise.vert InterpolationExercise.frag
_SHADER_CODE += HOffset.vert UpsideDown.vert PositionalColor.vert PositionalColor.frag TextureExercise.vert
_SHADER_CODE += TextureExercise.frag TextureReverse.frag TextureSimple.vert TextureSimple.frag

SHADER_CODE = $(addprefix ${SHADERD}/,${_SHADER_CODE})

########################################################################################
#   PROJECT DEFINITIONS
########################################################################################

TRIANGLE_EXERCISE_TARGET = HelloTriangle
TRIANGLE_EXERCISE_OBJ = ${EXAMPLEOBJD}/HelloTriangle.o 
TRIANGLE_EXERCISE_INCLUDE = 
TRIANGLE_EXERCISE_REQUISITES = ${TRIANGLE_EXERCISE_OBJ}
TRIANGLE_EXERCISE_LIBS = ${BASIC_LIBS}

TRIFORCE_EXERCISE_TARGET = HelloTriforce
TRIFORCE_EXERCISE_OBJ = ${EXAMPLEOBJD}/HelloTriforce2.o 
_TRIFORCE_OBJ = ${_SHADERS_OBJ}
TRIFORCE_OBJ = $(addprefix ${OBJD}/,${_TRIFORCE_OBJ})
TRIFORCE_EXERCISE_INCLUDE = 
TRIFORCE_EXERCISE_REQUISITES = ${TRIFORCE_EXERCISE_OBJ} ${SHADER_CODE} ${TRIFORCE_OBJ}
TRIFORCE_EXERCISE_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS}

RECTANGLE_EXERCISE_TARGET = HelloRectangle
RECTANGLE_EXERCISE_OBJ = ${EXAMPLEOBJD}/HelloRectangle.o
RECTANGLE_EXERCISE_INCLUDE = 
RECTANGLE_EXERCISE_REQUISITES = ${RECTANGLE_EXERCISE_OBJ}
RECTANGLE_EXERCISE_LIBS = ${BASIC_LIBS}

SHADER_EXERCISE_1_TARGET = ShaderExercise_1
SHADER_EXERCISE_1_OBJ = ${EXAMPLEOBJD}/ShaderExercise_1.o
_SHADER_1_OBJ = ${_SHADERS_OBJ}
SHADER_1_OBJ = $(addprefix ${OBJD}/,${_SHADER_1_OBJ})
SHADER_EXERCISE_1_INCLUDE = 
SHADER_EXERCISE_1_REQUISITES = ${SHADER_EXERCISE_1_OBJ} ${SHADER_CODE} ${SHADER_1_OBJ}
SHADER_EXERCISE_1_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS}

SHADER_EXERCISE_2_TARGET = ShaderExercise_2
SHADER_EXERCISE_2_OBJ = ${EXAMPLEOBJD}/ShaderExercise_2.o
_SHADER_2_OBJ  = ${_SHADERS_OBJ}
SHADER_2_OBJ = $(addprefix ${OBJD}/,${_SHADER_2_OBJ})
SHADER_EXERCISE_2_INCLUDE = 
SHADER_EXERCISE_2_REQUISITES = ${SHADER_EXERCISE_2_OBJ} ${SHADER_CODE} ${SHADER_2_OBJ}
SHADER_EXERCISE_2_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS}

TEXTURE_EXERCISE_1_TARGET = TextureExercise_1
TEXTURE_EXERCISE_1_OBJ = ${EXAMPLEOBJD}/TextureExercise_1.o
_TEXTURE_1_OBJ  = ${_SHADERS_OBJ}
TEXTURE_1_OBJ = $(addprefix ${OBJD}/,${_TEXTURE_1_OBJ})
TEXTURE_EXERCISE_1_INCLUDE = 
TEXTURE_EXERCISE_1_REQUISITES = ${TEXTURE_EXERCISE_1_OBJ} ${SHADER_CODE} ${TEXTURE_1_OBJ}
TEXTURE_EXERCISE_1_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS}

TEXTURE_EXERCISE_2_TARGET = TextureExercise_2
TEXTURE_EXERCISE_2_OBJ = ${EXAMPLEOBJD}/TextureExercise_2.o
_TEXTURE_2_OBJ  = ${_SHADERS_OBJ}
TEXTURE_2_OBJ = $(addprefix ${OBJD}/,${_TEXTURE_2_OBJ})
TEXTURE_EXERCISE_2_INCLUDE = 
TEXTURE_EXERCISE_2_REQUISITES = ${TEXTURE_EXERCISE_2_OBJ} ${SHADER_CODE} ${TEXTURE_2_OBJ}
TEXTURE_EXERCISE_2_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS}

TEXTURE_EXERCISE_3_TARGET = TextureExercise_3
TEXTURE_EXERCISE_3_OBJ = ${EXAMPLEOBJD}/TextureExercise_3.o
_TEXTURE_3_OBJ  = ${_SHADERS_OBJ}
TEXTURE_3_OBJ = $(addprefix ${OBJD}/,${_TEXTURE_3_OBJ})
TEXTURE_EXERCISE_3_INCLUDE = 
TEXTURE_EXERCISE_3_REQUISITES = ${TEXTURE_EXERCISE_3_OBJ} ${SHADER_CODE} ${TEXTURE_3_OBJ}
TEXTURE_EXERCISE_3_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS}

TEXTURE_EXERCISE_4_TARGET = TextureExercise_4
TEXTURE_EXERCISE_4_OBJ = ${EXAMPLEOBJD}/TextureExercise_4.o
_TEXTURE_4_OBJ  = ${_SHADERS_OBJ}
TEXTURE_4_OBJ = $(addprefix ${OBJD}/,${_TEXTURE_4_OBJ})
TEXTURE_EXERCISE_4_INCLUDE = 
TEXTURE_EXERCISE_4_REQUISITES = ${TEXTURE_EXERCISE_4_OBJ} ${SHADER_CODE} ${TEXTURE_4_OBJ}
TEXTURE_EXERCISE_4_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS}

TRANSFORM_EXERCISE_1_TARGET = TransformationsExercise_1
TRANSFORM_EXERCISE_1_OBJ = ${EXAMPLEOBJD}/TransformationsExercise_1.o
_TRANSFORM_1_OBJ  = ${_SHADERS_OBJ}
TRANSFORM_1_OBJ = $(addprefix ${OBJD}/,${_TRANSFORM_1_OBJ})
TRANSFORM_EXERCISE_1_INCLUDE = 
TRANSFORM_EXERCISE_1_REQUISITES = ${TRANSFORM_EXERCISE_1_OBJ} ${SHADER_CODE} ${TRANSFORM_1_OBJ}
TRANSFORM_EXERCISE_1_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS}

TRANSFORM_EXERCISE_2_TARGET = TransformationsExercise_2
TRANSFORM_EXERCISE_2_OBJ = ${EXAMPLEOBJD}/TransformationsExercise_2.o
_TRANSFORM_2_OBJ  = ${_SHADERS_OBJ}
TRANSFORM_2_OBJ = $(addprefix ${OBJD}/,${_TRANSFORM_2_OBJ})
TRANSFORM_EXERCISE_2_INCLUDE = 
TRANSFORM_EXERCISE_2_REQUISITES = ${TRANSFORM_EXERCISE_2_OBJ} ${SHADER_CODE} ${TRANSFORM_2_OBJ}
TRANSFORM_EXERCISE_2_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS}

COORD_SYSTEMS_EXERCISE_1_TARGET = CoordSystemsExercise_1
COORD_SYSTEMS_EXERCISE_1_OBJ = ${EXAMPLEOBJD}/CoordSystemsExercise_1.o
_COORD_SYSTEMS_1_OBJ  = ${_SHADERS_OBJ}
COORD_SYSTEMS_1_OBJ = $(addprefix ${OBJD}/,${_COORD_SYSTEMS_1_OBJ})
COORD_SYSTEMS_EXERCISE_1_INCLUDE = 
COORD_SYSTEMS_EXERCISE_1_REQUISITES = ${COORD_SYSTEMS_EXERCISE_1_OBJ} ${SHADER_CODE} ${COORD_SYSTEMS_1_OBJ}
COORD_SYSTEMS_EXERCISE_1_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS}

CAMERA_EXERCISE_1_TARGET = CameraExercise_1
CAMERA_EXERCISE_1_OBJ = ${EXAMPLEOBJD}/CameraExercise_1.o
_CAMERA_1_OBJ  = ${_SHADERS_OBJ}
CAMERA_1_OBJ = $(addprefix ${OBJD}/,${_CAMERA_1_OBJ})
CAMERA_EXERCISE_1_INCLUDE = 
CAMERA_EXERCISE_1_REQUISITES = ${CAMERA_EXERCISE_1_OBJ} ${SHADER_CODE} ${CAMERA_1_OBJ}
CAMERA_EXERCISE_1_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS}

CAMERA_EXERCISE_2_TARGET = CameraExercise_2
CAMERA_EXERCISE_2_OBJ = ${EXAMPLEOBJD}/CameraExercise_2.o
_CAMERA_2_OBJ  = ${_SHADERS_OBJ}
CAMERA_2_OBJ = $(addprefix ${OBJD}/,${_CAMERA_2_OBJ})
CAMERA_EXERCISE_2_INCLUDE = 
CAMERA_EXERCISE_2_REQUISITES = ${CAMERA_EXERCISE_2_OBJ} ${SHADER_CODE} ${CAMERA_2_OBJ}
CAMERA_EXERCISE_2_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS}

CAMERA_EXERCISE_3_TARGET = CameraExercise_3
CAMERA_EXERCISE_3_OBJ = ${EXAMPLEOBJD}/CameraExercise_3.o
_CAMERA_3_OBJ  = ${_SHADERS_OBJ} ${_GAMEOBJECTS_OBJ}
CAMERA_3_OBJ = $(addprefix ${OBJD}/,${_CAMERA_3_OBJ})
CAMERA_EXERCISE_3_INCLUDE = 
CAMERA_EXERCISE_3_REQUISITES = ${CAMERA_EXERCISE_3_OBJ} ${SHADER_CODE} ${CAMERA_3_OBJ}
CAMERA_EXERCISE_3_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS}

LIGHT_EXERCISE_TARGET = colorsExercise
LIGHT_EXERCISE_OBJ = ${EXAMPLEOBJD}/ColorsExercise_1.o
_LIGHT_OBJ  = ${_SHADERS_OBJ} ${_GAMEOBJECTS_OBJ}
LIGHT_OBJ = $(addprefix ${OBJD}/,${_LIGHT_OBJ})
LIGHT_EXERCISE_INCLUDE = 
LIGHT_EXERCISE_REQUISITES = ${LIGHT_EXERCISE_OBJ} ${SHADER_CODE} ${LIGHT_OBJ}
LIGHT_EXERCISE_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS}

MATERIAL_EXERCISE_1_TARGET = MaterialsExercise_1
MATERIAL_EXERCISE_1_OBJ = ${EXAMPLEOBJD}/MaterialsExercise_1.o
_MATERIAL_1_OBJ  = ${_SHADERS_OBJ} ${_GAMEOBJECTS_OBJ}
MATERIAL_1_OBJ = $(addprefix ${OBJD}/,${_MATERIAL_1_OBJ})
MATERIAL_EXERCISE_1_INCLUDE = 
MATERIAL_EXERCISE_1_REQUISITES = ${MATERIAL_EXERCISE_1_OBJ} ${SHADER_CODE} ${MATERIAL_1_OBJ}
MATERIAL_EXERCISE_1_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS}

MATERIAL_EXERCISE_2_TARGET = MaterialsExercise_2
MATERIAL_EXERCISE_2_OBJ = ${EXAMPLEOBJD}/MaterialsExercise_2.o
_MATERIAL_2_OBJ  = ${_SHADERS_OBJ} ${_GAMEOBJECTS_OBJ}
MATERIAL_2_OBJ = $(addprefix ${OBJD}/,${_MATERIAL_2_OBJ})
MATERIAL_EXERCISE_2_INCLUDE = 
MATERIAL_EXERCISE_2_REQUISITES = ${MATERIAL_EXERCISE_2_OBJ} ${SHADER_CODE} ${MATERIAL_2_OBJ}
MATERIAL_EXERCISE_2_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS}

MATERIAL_EXERCISE_3_TARGET = MaterialsExercise_3
MATERIAL_EXERCISE_3_OBJ = ${EXAMPLEOBJD}/MaterialsExercise_3.o
_MATERIAL_3_OBJ  = ${_SHADERS_OBJ} ${_GAMEOBJECTS_OBJ}
MATERIAL_3_OBJ = $(addprefix ${OBJD}/,${_MATERIAL_3_OBJ})
MATERIAL_EXERCISE_3_INCLUDE = 
MATERIAL_EXERCISE_3_REQUISITES = ${MATERIAL_EXERCISE_3_OBJ} ${SHADER_CODE} ${MATERIAL_3_OBJ}
MATERIAL_EXERCISE_3_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS}

LIGHT_DIRECTIONAL_EXERCISE_TARGET = LightDirectionalExercise
LIGHT_DIRECTIONAL_EXERCISE_OBJ = ${EXAMPLEOBJD}/LightDirectionalExercise.o
_LIGHT_DIRECTIONAL_OBJ  = ${_SHADERS_OBJ} ${_GAMEOBJECTS_OBJ}
LIGHT_DIRECTIONAL_OBJ = $(addprefix ${OBJD}/,${_LIGHT_DIRECTIONAL_OBJ})
LIGHT_DIRECTIONAL_EXERCISE_INCLUDE = 
LIGHT_DIRECTIONAL_EXERCISE_REQUISITES = ${LIGHT_DIRECTIONAL_EXERCISE_OBJ} ${SHADER_CODE} ${LIGHT_DIRECTIONAL_OBJ}
LIGHT_DIRECTIONAL_EXERCISE_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS}

LIGHT_ATTENUATION_EXERCISE_TARGET = LightAttenuationExercise
LIGHT_ATTENUATION_EXERCISE_OBJ = ${EXAMPLEOBJD}/LightAttenuationExercise.o
_LIGHT_ATTENUATION_OBJ  = ${_SHADERS_OBJ} ${_GAMEOBJECTS_OBJ}
LIGHT_ATTENUATION_OBJ = $(addprefix ${OBJD}/,${_LIGHT_ATTENUATION_OBJ})
LIGHT_ATTENUATION_EXERCISE_INCLUDE = 
LIGHT_ATTENUATION_EXERCISE_REQUISITES = ${LIGHT_ATTENUATION_EXERCISE_OBJ} ${SHADER_CODE} ${LIGHT_ATTENUATION_OBJ}
LIGHT_ATTENUATION_EXERCISE_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS}

LIGHT_FLASHLIGHT_EXERCISE_TARGET = LightFlashlightExercise
LIGHT_FLASHLIGHT_EXERCISE_OBJ = ${EXAMPLEOBJD}/LightFlashlightExercise.o
_LIGHT_FLASHLIGHT_OBJ  = ${_SHADERS_OBJ} ${_GAMEOBJECTS_OBJ}
LIGHT_FLASHLIGHT_OBJ = $(addprefix ${OBJD}/,${_LIGHT_FLASHLIGHT_OBJ})
LIGHT_FLASHLIGHT_EXERCISE_INCLUDE = 
LIGHT_FLASHLIGHT_EXERCISE_REQUISITES = ${LIGHT_FLASHLIGHT_EXERCISE_OBJ} ${SHADER_CODE} ${LIGHT_FLASHLIGHT_OBJ}
LIGHT_FLASHLIGHT_EXERCISE_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS}

LIGHT_MULTILIGHT_EXERCISE_TARGET = LightMultipleExercise
LIGHT_MULTILIGHT_EXERCISE_OBJ = ${EXAMPLEOBJD}/LightMultipleExercise.o
_LIGHT_MULTILIGHT_OBJ  = ${_SHADERS_OBJ} ${_GAMEOBJECTS_OBJ}
LIGHT_MULTILIGHT_OBJ = $(addprefix ${OBJD}/,${_LIGHT_MULTILIGHT_OBJ})
LIGHT_MULTILIGHT_EXERCISE_INCLUDE = 
LIGHT_MULTILIGHT_EXERCISE_REQUISITES = ${LIGHT_MULTILIGHT_EXERCISE_OBJ} ${SHADER_CODE} ${LIGHT_MULTILIGHT_OBJ}
LIGHT_MULTILIGHT_EXERCISE_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS}

MODEL_EXERCISE_TARGET = ModelExercise
MODEL_EXERCISE_OBJ = ${EXAMPLEOBJD}/ModelExercise.o
_MODEL_OBJ  = ${_SHADERS_OBJ} ${_GAMEOBJECTS_OBJ} ${_ASSIMP_OBJ}
MODEL_OBJ = $(addprefix ${OBJD}/,${_MODEL_OBJ})
MODEL_EXERCISE_INCLUDE = 
MODEL_EXERCISE_REQUISITES = ${MODEL_EXERCISE_OBJ} ${SHADER_CODE} ${MODEL_OBJ}
MODEL_EXERCISE_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS} ${MODEL_LIBS}

DEPTH_TESTING_EXERCISE_TARGET = DepthTestingExercise
DEPTH_TESTING_EXERCISE_OBJ = ${EXAMPLEOBJD}/DepthTestingExercise.o
_DEPTH_TESTING_OBJ  = ${_SHADERS_OBJ} ${_GAMEOBJECTS_OBJ} ${_ASSIMP_OBJ}
DEPTH_TESTING_OBJ = $(addprefix ${OBJD}/,${_DEPTH_TESTING_OBJ})
DEPTH_TESTING_EXERCISE_INCLUDE = 
DEPTH_TESTING_EXERCISE_REQUISITES = ${DEPTH_TESTING_EXERCISE_OBJ} ${SHADER_CODE} ${DEPTH_TESTING_OBJ}
DEPTH_TESTING_EXERCISE_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS} ${MODEL_LIBS}

STENCIL_TESTING_EXERCISE_TARGET = StencilTestingExercise
STENCIL_TESTING_EXERCISE_OBJ = ${EXAMPLEOBJD}/StencilTestingExercise.o
_STENCIL_TESTING_OBJ  = ${_SHADERS_OBJ} ${_GAMEOBJECTS_OBJ} ${_ASSIMP_OBJ}
STENCIL_TESTING_OBJ = $(addprefix ${OBJD}/,${_STENCIL_TESTING_OBJ})
STENCIL_TESTING_EXERCISE_INCLUDE = 
STENCIL_TESTING_EXERCISE_REQUISITES = ${STENCIL_TESTING_EXERCISE_OBJ} ${SHADER_CODE} ${STENCIL_TESTING_OBJ}
STENCIL_TESTING_EXERCISE_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS} ${MODEL_LIBS}

TRANSPARENCY_EXERCISE_TARGET = TransparencyExercise
TRANSPARENCY_EXERCISE_OBJ = ${EXAMPLEOBJD}/TransparencyExercise.o
_TRANSPARENCY_OBJ  = ${_SHADERS_OBJ} ${_GAMEOBJECTS_OBJ} ${_ASSIMP_OBJ}
TRANSPARENCY_OBJ = $(addprefix ${OBJD}/,${_TRANSPARENCY_OBJ})
TRANSPARENCY_EXERCISE_INCLUDE = 
TRANSPARENCY_EXERCISE_REQUISITES = ${TRANSPARENCY_EXERCISE_OBJ} ${SHADER_CODE} ${TRANSPARENCY_OBJ}
TRANSPARENCY_EXERCISE_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS} ${MODEL_LIBS}

POST_PROCESSING_EXERCISE_TARGET = PostProcessingExercise
POST_PROCESSING_EXERCISE_OBJ = ${EXAMPLEOBJD}/PostProcessingExercise.o 
_POST_PROCESSING_OBJ = ${_SHADERS_OBJ} ${_GAMEOBJECTS_OBJ} ${_ASSIMP_OBJ}
POST_PROCESSING_OBJ = $(addprefix ${OBJD}/,${_POST_PROCESSING_OBJ})
POST_PROCESSING_EXERCISE_INCLUDE = 
POST_PROCESSING_EXERCISE_REQUISITES = ${POST_PROCESSING_EXERCISE_OBJ} ${SHADER_CODE} ${POST_PROCESSING_OBJ}
POST_PROCESSING_EXERCISE_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS} ${MODEL_LIBS}

CUBE_MAP_EXERCISE_TARGET = CubeMapExercise
CUBE_MAP_EXERCISE_OBJ = ${EXAMPLEOBJD}/CubeMapExercise.o 
_CUBE_MAP_OBJ = ${_SHADERS_OBJ} ${_GAMEOBJECTS_OBJ} ${_ASSIMP_OBJ}
CUBE_MAP_OBJ = $(addprefix ${OBJD}/,${_CUBE_MAP_OBJ})
CUBE_MAP_EXERCISE_INCLUDE = 
CUBE_MAP_EXERCISE_REQUISITES = ${CUBE_MAP_EXERCISE_OBJ} ${SHADER_CODE} ${CUBE_MAP_OBJ}
CUBE_MAP_EXERCISE_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS} ${MODEL_LIBS}

CELLULAR_AUTOMATA_1D_EXERCISE_TARGET = CellularAutomata1DExercise
CELLULAR_AUTOMATA_1D_EXERCISE_OBJ = ${EXAMPLEOBJD}/CellularAutomata1DExercise.o
_CELLULAR_AUTOMATA_1D_OBJ = ${_SHADERS_OBJ} ${_GAMEOBJECTS_OBJ} ${_ASSIMP_OBJ}
CELLULAR_AUTOMATA_1D_OBJ = $(addprefix ${OBJD}/,${_CELLULAR_AUTOMATA_1D_OBJ})
CELLULAR_AUTOMATA_1D_EXERCISE_INCLUDE = 
CELLULAR_AUTOMATA_1D_EXERCISE_REQUISITES = ${CELLULAR_AUTOMATA_1D_EXERCISE_OBJ} ${SHADER_CODE} ${CELLULAR_AUTOMATA_1D_OBJ}
CELLULAR_AUTOMATA_1D_EXERCISE_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS} ${MODEL_LIBS}

GENERAL_1D_CELLULAR_AUTOMATA_TARGET = General1DCellularAutomata
__GENERAL_1D_CELLULAR_AUTOMATA_OBJ = ${EXAMPLEOBJD}/General1DCellularAutomata.o
_GENERAL_1D_CELLULAR_AUTOMATA_OBJ = ${_SHADERS_OBJ} ${_GAMEOBJECTS_OBJ} ${_ASSIMP_OBJ}
GENERAL_1D_CELLULAR_AUTOMATA_OBJ = $(addprefix ${OBJD}/,${_GENERAL_1D_CELLULAR_AUTOMATA_OBJ})
GENERAL_1D_CELLULAR_AUTOMATA_INCLUDE = 
GENERAL_1D_CELLULAR_AUTOMATA_REQUISITES = ${__GENERAL_1D_CELLULAR_AUTOMATA_OBJ} ${SHADER_CODE} ${GENERAL_1D_CELLULAR_AUTOMATA_OBJ}
GENERAL_1D_CELLULAR_AUTOMATA_LIBS = ${BASIC_LIBS} ${IMAGE_LIBS} ${MODEL_LIBS}

########################################################################################
#   TARGET OF PROJECTS TO COMPILE
########################################################################################

BASIC_TARGETS     = ${TRIANGLE_EXERCISE_TARGET} ${RECTANGLE_EXERCISE_TARGET} ${TRIFORCE_EXERCISE_TARGET} ${SHADER_EXERCISE_1_TARGET} ${SHADER_EXERCISE_2_TARGET}
BASIC_TARGETS    += ${TEXTURE_EXERCISE_1_TARGET} ${TEXTURE_EXERCISE_2_TARGET} ${TEXTURE_EXERCISE_3_TARGET} ${TEXTURE_EXERCISE_4_TARGET}

3D_TARGETS        = ${TRANSFORM_EXERCISE_1_TARGET} ${TRANSFORM_EXERCISE_2_TARGET} ${COORD_SYSTEMS_EXERCISE_1_TARGET} ${CAMERA_EXERCISE_1_TARGET}
3D_TARGETS       += ${CAMERA_EXERCISE_2_TARGET} ${CAMERA_EXERCISE_3_TARGET}

LIGHT_TARGETS     = ${LIGHT_EXERCISE_TARGET} ${MATERIAL_EXERCISE_1_TARGET} ${MATERIAL_EXERCISE_2_TARGET} ${MATERIAL_EXERCISE_3_TARGET}
LIGHT_TARGETS    += ${LIGHT_DIRECTIONAL_EXERCISE_TARGET} ${LIGHT_ATTENUATION_EXERCISE_TARGET} ${LIGHT_FLASHLIGHT_EXERCISE_TARGET}
LIGHT_TARGETS    += ${LIGHT_MULTILIGHT_EXERCISE_TARGET}

ADVANCED_TARGETS  = ${MODEL_EXERCISE_TARGET} ${DEPTH_TESTING_EXERCISE_TARGET} ${STENCIL_TESTING_EXERCISE_TARGET} ${TRANSPARENCY_EXERCISE_TARGET}
ADVANCED_TARGETS += ${POST_PROCESSING_EXERCISE_TARGET} ${CUBE_MAP_EXERCISE_TARGET} ${CELLULAR_AUTOMATA_1D_EXERCISE_TARGET} ${GENERAL_1D_CELLULAR_AUTOMATA_TARGET}




ALL_TARGETS       = ${BASIC_TARGETS} ${3D_TARGETS} ${LIGHT_TARGETS} ${ADVANCED_TARGETS}



########################################################################################
#   MAKEFILE RULES
########################################################################################

all: ${ALL_TARGETS}

basic: ${BASIC_TARGETS}

3d: ${3D_TARGETS}

advanced: ${ADVANCED_TARGETS}

clean:
	-rm -f ${BUILD}/*


########################################################################################
# PROJECT RULES
########################################################################################

${TRIANGLE_EXERCISE_TARGET}: ${TRIANGLE_EXERCISE_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${TRIANGLE_EXERCISE_OBJ} ${TRIANGLE_EXERCISE_LIBS}

${RECTANGLE_EXERCISE_TARGET}: ${RECTANGLE_EXERCISE_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${RECTANGLE_EXERCISE_OBJ} ${RECTANGLE_EXERCISE_LIBS}

${TRIFORCE_EXERCISE_TARGET}: ${TRIFORCE_EXERCISE_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${TRIFORCE_EXERCISE_OBJ} ${TRIFORCE_OBJ} ${TRIFORCE_EXERCISE_LIBS}

${SHADER_EXERCISE_1_TARGET}: ${SHADER_EXERCISE_1_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${SHADER_EXERCISE_1_OBJ} ${SHADER_1_OBJ} ${SHADER_EXERCISE_1_LIBS}

${SHADER_EXERCISE_2_TARGET}: ${SHADER_EXERCISE_2_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${SHADER_EXERCISE_2_OBJ} ${SHADER_2_OBJ} ${SHADER_EXERCISE_2_LIBS}

${TEXTURE_EXERCISE_1_TARGET}: ${TEXTURE_EXERCISE_1_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${TEXTURE_EXERCISE_1_OBJ} ${TEXTURE_1_OBJ} ${TEXTURE_EXERCISE_1_LIBS}

${TEXTURE_EXERCISE_2_TARGET}: ${TEXTURE_EXERCISE_2_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${TEXTURE_EXERCISE_2_OBJ} ${TEXTURE_2_OBJ} ${TEXTURE_EXERCISE_2_LIBS}

${TEXTURE_EXERCISE_3_TARGET}: ${TEXTURE_EXERCISE_3_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${TEXTURE_EXERCISE_3_OBJ} ${TEXTURE_3_OBJ} ${TEXTURE_EXERCISE_3_LIBS}

${TEXTURE_EXERCISE_4_TARGET}: ${TEXTURE_EXERCISE_4_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${TEXTURE_EXERCISE_4_OBJ} ${TEXTURE_4_OBJ} ${TEXTURE_EXERCISE_4_LIBS}

${TRANSFORM_EXERCISE_1_TARGET}: ${TRANSFORM_EXERCISE_1_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${TRANSFORM_EXERCISE_1_OBJ} ${TRANSFORM_1_OBJ} ${TRANSFORM_EXERCISE_1_LIBS}

${TRANSFORM_EXERCISE_2_TARGET}: ${TRANSFORM_EXERCISE_2_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${TRANSFORM_EXERCISE_2_OBJ} ${TRANSFORM_2_OBJ} ${TRANSFORM_EXERCISE_2_LIBS}

${COORD_SYSTEMS_EXERCISE_1_TARGET}: ${COORD_SYSTEMS_EXERCISE_1_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${COORD_SYSTEMS_EXERCISE_1_OBJ} ${COORD_SYSTEMS_1_OBJ} ${COORD_SYSTEMS_EXERCISE_1_LIBS}

${CAMERA_EXERCISE_1_TARGET}: ${CAMERA_EXERCISE_1_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${CAMERA_EXERCISE_1_OBJ} ${CAMERA_1_OBJ} ${CAMERA_EXERCISE_1_LIBS}

${CAMERA_EXERCISE_2_TARGET}: ${CAMERA_EXERCISE_2_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${CAMERA_EXERCISE_2_OBJ} ${CAMERA_2_OBJ} ${CAMERA_EXERCISE_2_LIBS}

${CAMERA_EXERCISE_3_TARGET}: ${CAMERA_EXERCISE_3_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${CAMERA_EXERCISE_3_OBJ} ${CAMERA_3_OBJ} ${CAMERA_EXERCISE_3_LIBS}

${LIGHT_EXERCISE_TARGET}: ${LIGHT_EXERCISE_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${LIGHT_EXERCISE_OBJ} ${LIGHT_OBJ} ${LIGHT_EXERCISE_LIBS}

${MATERIAL_EXERCISE_1_TARGET}: ${MATERIAL_EXERCISE_1_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${MATERIAL_EXERCISE_1_OBJ} ${MATERIAL_1_OBJ} ${MATERIAL_EXERCISE_1_LIBS}

${MATERIAL_EXERCISE_2_TARGET}: ${MATERIAL_EXERCISE_2_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${MATERIAL_EXERCISE_2_OBJ} ${MATERIAL_2_OBJ} ${MATERIAL_EXERCISE_2_LIBS}

${MATERIAL_EXERCISE_3_TARGET}: ${MATERIAL_EXERCISE_3_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${MATERIAL_EXERCISE_3_OBJ} ${MATERIAL_3_OBJ} ${MATERIAL_EXERCISE_3_LIBS}

${LIGHT_DIRECTIONAL_EXERCISE_TARGET}: ${LIGHT_DIRECTIONAL_EXERCISE_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${LIGHT_DIRECTIONAL_EXERCISE_OBJ} ${LIGHT_DIRECTIONAL_OBJ} ${LIGHT_DIRECTIONAL_EXERCISE_LIBS}

${LIGHT_ATTENUATION_EXERCISE_TARGET}: ${LIGHT_ATTENUATION_EXERCISE_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${LIGHT_ATTENUATION_EXERCISE_OBJ} ${LIGHT_ATTENUATION_OBJ} ${LIGHT_ATTENUATION_EXERCISE_LIBS}

${LIGHT_FLASHLIGHT_EXERCISE_TARGET}: ${LIGHT_FLASHLIGHT_EXERCISE_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${LIGHT_FLASHLIGHT_EXERCISE_OBJ} ${LIGHT_FLASHLIGHT_OBJ} ${LIGHT_FLASHLIGHT_EXERCISE_LIBS}

${LIGHT_MULTILIGHT_EXERCISE_TARGET}: ${LIGHT_MULTILIGHT_EXERCISE_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${LIGHT_MULTILIGHT_EXERCISE_OBJ} ${LIGHT_MULTILIGHT_OBJ} ${LIGHT_MULTILIGHT_EXERCISE_LIBS}

${MODEL_EXERCISE_TARGET}: ${MODEL_EXERCISE_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${MODEL_EXERCISE_OBJ} ${MODEL_OBJ} ${MODEL_EXERCISE_LIBS}

${DEPTH_TESTING_EXERCISE_TARGET}: ${DEPTH_TESTING_EXERCISE_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${DEPTH_TESTING_EXERCISE_OBJ} ${DEPTH_TESTING_OBJ} ${DEPTH_TESTING_EXERCISE_LIBS}

${STENCIL_TESTING_EXERCISE_TARGET}: ${STENCIL_TESTING_EXERCISE_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${STENCIL_TESTING_EXERCISE_OBJ} ${STENCIL_TESTING_OBJ} ${STENCIL_TESTING_EXERCISE_LIBS}

${TRANSPARENCY_EXERCISE_TARGET}: ${TRANSPARENCY_EXERCISE_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${TRANSPARENCY_EXERCISE_OBJ} ${TRANSPARENCY_OBJ} ${TRANSPARENCY_EXERCISE_LIBS}

${POST_PROCESSING_EXERCISE_TARGET}: ${POST_PROCESSING_EXERCISE_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${POST_PROCESSING_EXERCISE_OBJ} ${POST_PROCESSING_OBJ} ${POST_PROCESSING_EXERCISE_LIBS}

${CUBE_MAP_EXERCISE_TARGET}: ${CUBE_MAP_EXERCISE_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${CUBE_MAP_EXERCISE_OBJ} ${CUBE_MAP_OBJ} ${CUBE_MAP_EXERCISE_LIBS}

${CELLULAR_AUTOMATA_1D_EXERCISE_TARGET}: ${CELLULAR_AUTOMATA_1D_EXERCISE_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${CELLULAR_AUTOMATA_1D_EXERCISE_OBJ} ${CELLULAR_AUTOMATA_1D_OBJ} ${CELLULAR_AUTOMATA_1D_EXERCISE_LIBS}

${GENERAL_1D_CELLULAR_AUTOMATA_TARGET}: ${GENERAL_1D_CELLULAR_AUTOMATA_REQUISITES}
	${CC} ${CFLAGS} -o ${BUILD}/$@ ${__GENERAL_1D_CELLULAR_AUTOMATA_OBJ} ${GENERAL_1D_CELLULAR_AUTOMATA_OBJ} ${GENERAL_1D_CELLULAR_AUTOMATA_LIBS}

${BUILD}/%.o: ${SRCD}/%.cpp
	${CC} ${CFLAGS} ${INCLUDES} -c $< -o $@

${EXAMPLEOBJD}/%.o: ${EXAMPLED}/%.cpp
	${CC} ${CFLAGS} ${INCLUDES} -c $< -o $@
